In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from urllib.request import urlretrieve

In [ ]:
urlretrieve("https://raw.githubusercontent.com/tempoloud/mlrecord/main/preprocessing.csv", "./data.csv")

('./data.csv', <http.client.HTTPMessage at 0x7f090ba7cfa0>)

In [ ]:
dataset = pd.read_csv('./data.csv')

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

In [ ]:
x = dataset.iloc[:, :3]
y = dataset.iloc[:, 3]

In [ ]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encode_x = LabelEncoder()

In [ ]:
x.iloc[:,0] = label_encode_x.fit_transform(x.iloc[:,0])

<ipython-input-12-5036aa7efded>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.iloc[:,0] = label_encode_x.fit_transform(x.iloc[:,0])


In [ ]:
x

Country   Age   Salary
0        0  44.0  72000.0
1        2  27.0  48000.0
2        1  30.0  54000.0
3        2  38.0  61000.0
4        1  40.0      NaN
5        0  35.0  58000.0
6        2   NaN  52000.0
7        0  48.0  79000.0
8        1  50.0  83000.0
9        0  37.0  67000.0

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Country  10 non-null     int64  
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 368.0 bytes


In [ ]:
x['Age'].fillna(x['Age'].mean(), inplace= True)

In [ ]:
x['Salary'].fillna(x['Salary'].mean(), inplace= True)

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Country  10 non-null     int64  
 1   Age      10 non-null     float64
 2   Salary   10 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 368.0 bytes


In [ ]:
x

Country        Age        Salary
0        0  44.000000  72000.000000
1        2  27.000000  48000.000000
2        1  30.000000  54000.000000
3        2  38.000000  61000.000000
4        1  40.000000  63777.777778
5        0  35.000000  58000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
8        1  50.000000  83000.000000
9        0  37.000000  67000.000000

In [ ]:
y = LabelEncoder().fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train

Country        Age        Salary
4        1  40.000000  63777.777778
9        0  37.000000  67000.000000
1        2  27.000000  48000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
3        2  38.000000  61000.000000
0        0  44.000000  72000.000000
5        0  35.000000  58000.000000

In [ ]:
x_test

Country   Age   Salary
2        1  30.0  54000.0
8        1  50.0  83000.0

In [ ]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:
y_test

array([0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc_x = StandardScaler()

In [ ]:
x_train_scale = sc_x.fit_transform(x_train)

In [ ]:
x_train_scale

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [ ]:
x_test_scale = sc_x.fit_transform(x_test)

In [ ]:
x_test_scale

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])